// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_pty.proto

package com.lenovo.husky.docker;

public final class TestPTYProtocol {
  private TestPTYProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CmdRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CmdRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes body = 1;</code>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code CmdRequest}
   */
  public  static final class CmdRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CmdRequest)
      CmdRequestOrBuilder {
    // Use CmdRequest.newBuilder() to construct.
    private CmdRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CmdRequest() {
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CmdRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              body_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lenovo.husky.docker.TestPTYProtocol.internal_static_CmdRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lenovo.husky.docker.TestPTYProtocol.internal_static_CmdRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lenovo.husky.docker.TestPTYProtocol.CmdRequest.class, com.lenovo.husky.docker.TestPTYProtocol.CmdRequest.Builder.class);
    }

    public static final int BODY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>optional bytes body = 1;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!body_.isEmpty()) {
        output.writeBytes(1, body_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, body_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lenovo.husky.docker.TestPTYProtocol.CmdRequest)) {
        return super.equals(obj);
      }
      com.lenovo.husky.docker.TestPTYProtocol.CmdRequest other = (com.lenovo.husky.docker.TestPTYProtocol.CmdRequest) obj;

      boolean result = true;
      result = result && getBody()
          .equals(other.getBody());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lenovo.husky.docker.TestPTYProtocol.CmdRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lenovo.husky.docker.TestPTYProtocol.CmdRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lenovo.husky.docker.TestPTYProtocol.CmdRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lenovo.husky.docker.TestPTYProtocol.CmdRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lenovo.husky.docker.TestPTYProtocol.CmdRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.lenovo.husky.docker.TestPTYProtocol.CmdRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lenovo.husky.docker.TestPTYProtocol.CmdRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lenovo.husky.docker.TestPTYProtocol.CmdRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lenovo.husky.docker.TestPTYProtocol.CmdRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.lenovo.husky.docker.TestPTYProtocol.CmdRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lenovo.husky.docker.TestPTYProtocol.CmdRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CmdRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CmdRequest)
        com.lenovo.husky.docker.TestPTYProtocol.CmdRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lenovo.husky.docker.TestPTYProtocol.internal_static_CmdRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lenovo.husky.docker.TestPTYProtocol.internal_static_CmdRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lenovo.husky.docker.TestPTYProtocol.CmdRequest.class, com.lenovo.husky.docker.TestPTYProtocol.CmdRequest.Builder.class);
      }

      // Construct using com.lenovo.husky.docker.TestPTYProtocol.CmdRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        body_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lenovo.husky.docker.TestPTYProtocol.internal_static_CmdRequest_descriptor;
      }

      public com.lenovo.husky.docker.TestPTYProtocol.CmdRequest getDefaultInstanceForType() {
        return com.lenovo.husky.docker.TestPTYProtocol.CmdRequest.getDefaultInstance();
      }

      public com.lenovo.husky.docker.TestPTYProtocol.CmdRequest build() {
        com.lenovo.husky.docker.TestPTYProtocol.CmdRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lenovo.husky.docker.TestPTYProtocol.CmdRequest buildPartial() {
        com.lenovo.husky.docker.TestPTYProtocol.CmdRequest result = new com.lenovo.husky.docker.TestPTYProtocol.CmdRequest(this);
        result.body_ = body_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lenovo.husky.docker.TestPTYProtocol.CmdRequest) {
          return mergeFrom((com.lenovo.husky.docker.TestPTYProtocol.CmdRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lenovo.husky.docker.TestPTYProtocol.CmdRequest other) {
        if (other == com.lenovo.husky.docker.TestPTYProtocol.CmdRequest.getDefaultInstance()) return this;
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lenovo.husky.docker.TestPTYProtocol.CmdRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lenovo.husky.docker.TestPTYProtocol.CmdRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes body = 1;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>optional bytes body = 1;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes body = 1;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:CmdRequest)
    }

    // @@protoc_insertion_point(class_scope:CmdRequest)
    private static final com.lenovo.husky.docker.TestPTYProtocol.CmdRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lenovo.husky.docker.TestPTYProtocol.CmdRequest();
    }

    public static com.lenovo.husky.docker.TestPTYProtocol.CmdRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CmdRequest>
        PARSER = new com.google.protobuf.AbstractParser<CmdRequest>() {
      public CmdRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CmdRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CmdRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CmdRequest> getParserForType() {
      return PARSER;
    }

    public com.lenovo.husky.docker.TestPTYProtocol.CmdRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CmdResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CmdResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes body = 1;</code>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code CmdResponse}
   */
  public  static final class CmdResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CmdResponse)
      CmdResponseOrBuilder {
    // Use CmdResponse.newBuilder() to construct.
    private CmdResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CmdResponse() {
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CmdResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              body_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lenovo.husky.docker.TestPTYProtocol.internal_static_CmdResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lenovo.husky.docker.TestPTYProtocol.internal_static_CmdResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lenovo.husky.docker.TestPTYProtocol.CmdResponse.class, com.lenovo.husky.docker.TestPTYProtocol.CmdResponse.Builder.class);
    }

    public static final int BODY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>optional bytes body = 1;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!body_.isEmpty()) {
        output.writeBytes(1, body_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, body_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lenovo.husky.docker.TestPTYProtocol.CmdResponse)) {
        return super.equals(obj);
      }
      com.lenovo.husky.docker.TestPTYProtocol.CmdResponse other = (com.lenovo.husky.docker.TestPTYProtocol.CmdResponse) obj;

      boolean result = true;
      result = result && getBody()
          .equals(other.getBody());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lenovo.husky.docker.TestPTYProtocol.CmdResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lenovo.husky.docker.TestPTYProtocol.CmdResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lenovo.husky.docker.TestPTYProtocol.CmdResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lenovo.husky.docker.TestPTYProtocol.CmdResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lenovo.husky.docker.TestPTYProtocol.CmdResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.lenovo.husky.docker.TestPTYProtocol.CmdResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lenovo.husky.docker.TestPTYProtocol.CmdResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lenovo.husky.docker.TestPTYProtocol.CmdResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lenovo.husky.docker.TestPTYProtocol.CmdResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.lenovo.husky.docker.TestPTYProtocol.CmdResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lenovo.husky.docker.TestPTYProtocol.CmdResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CmdResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CmdResponse)
        com.lenovo.husky.docker.TestPTYProtocol.CmdResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lenovo.husky.docker.TestPTYProtocol.internal_static_CmdResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lenovo.husky.docker.TestPTYProtocol.internal_static_CmdResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lenovo.husky.docker.TestPTYProtocol.CmdResponse.class, com.lenovo.husky.docker.TestPTYProtocol.CmdResponse.Builder.class);
      }

      // Construct using com.lenovo.husky.docker.TestPTYProtocol.CmdResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        body_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lenovo.husky.docker.TestPTYProtocol.internal_static_CmdResponse_descriptor;
      }

      public com.lenovo.husky.docker.TestPTYProtocol.CmdResponse getDefaultInstanceForType() {
        return com.lenovo.husky.docker.TestPTYProtocol.CmdResponse.getDefaultInstance();
      }

      public com.lenovo.husky.docker.TestPTYProtocol.CmdResponse build() {
        com.lenovo.husky.docker.TestPTYProtocol.CmdResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lenovo.husky.docker.TestPTYProtocol.CmdResponse buildPartial() {
        com.lenovo.husky.docker.TestPTYProtocol.CmdResponse result = new com.lenovo.husky.docker.TestPTYProtocol.CmdResponse(this);
        result.body_ = body_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lenovo.husky.docker.TestPTYProtocol.CmdResponse) {
          return mergeFrom((com.lenovo.husky.docker.TestPTYProtocol.CmdResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lenovo.husky.docker.TestPTYProtocol.CmdResponse other) {
        if (other == com.lenovo.husky.docker.TestPTYProtocol.CmdResponse.getDefaultInstance()) return this;
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lenovo.husky.docker.TestPTYProtocol.CmdResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lenovo.husky.docker.TestPTYProtocol.CmdResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes body = 1;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>optional bytes body = 1;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes body = 1;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:CmdResponse)
    }

    // @@protoc_insertion_point(class_scope:CmdResponse)
    private static final com.lenovo.husky.docker.TestPTYProtocol.CmdResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lenovo.husky.docker.TestPTYProtocol.CmdResponse();
    }

    public static com.lenovo.husky.docker.TestPTYProtocol.CmdResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CmdResponse>
        PARSER = new com.google.protobuf.AbstractParser<CmdResponse>() {
      public CmdResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CmdResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CmdResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CmdResponse> getParserForType() {
      return PARSER;
    }

    public com.lenovo.husky.docker.TestPTYProtocol.CmdResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  /**
   * Protobuf service {@code PTYService}
   */
  public static abstract class PTYService
      implements com.google.protobuf.Service {
    protected PTYService() {}

    public interface Interface {
      /**
       * <code>rpc command(.CmdRequest) returns (stream .CmdResponse);</code>
       */
      public abstract void command(
          com.google.protobuf.RpcController controller,
          com.lenovo.husky.docker.TestPTYProtocol.CmdRequest request,
          com.google.protobuf.RpcCallback<com.lenovo.husky.docker.TestPTYProtocol.CmdResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new PTYService() {
        @java.lang.Override
        public  void command(
            com.google.protobuf.RpcController controller,
            com.lenovo.husky.docker.TestPTYProtocol.CmdRequest request,
            com.google.protobuf.RpcCallback<com.lenovo.husky.docker.TestPTYProtocol.CmdResponse> done) {
          impl.command(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.command(controller, (com.lenovo.husky.docker.TestPTYProtocol.CmdRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.lenovo.husky.docker.TestPTYProtocol.CmdRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.lenovo.husky.docker.TestPTYProtocol.CmdResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc command(.CmdRequest) returns (stream .CmdResponse);</code>
     */
    public abstract void command(
        com.google.protobuf.RpcController controller,
        com.lenovo.husky.docker.TestPTYProtocol.CmdRequest request,
        com.google.protobuf.RpcCallback<com.lenovo.husky.docker.TestPTYProtocol.CmdResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.lenovo.husky.docker.TestPTYProtocol.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.command(controller, (com.lenovo.husky.docker.TestPTYProtocol.CmdRequest)request,
            com.google.protobuf.RpcUtil.<com.lenovo.husky.docker.TestPTYProtocol.CmdResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.lenovo.husky.docker.TestPTYProtocol.CmdRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.lenovo.husky.docker.TestPTYProtocol.CmdResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.lenovo.husky.docker.TestPTYProtocol.PTYService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void command(
          com.google.protobuf.RpcController controller,
          com.lenovo.husky.docker.TestPTYProtocol.CmdRequest request,
          com.google.protobuf.RpcCallback<com.lenovo.husky.docker.TestPTYProtocol.CmdResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.lenovo.husky.docker.TestPTYProtocol.CmdResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.lenovo.husky.docker.TestPTYProtocol.CmdResponse.class,
            com.lenovo.husky.docker.TestPTYProtocol.CmdResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.lenovo.husky.docker.TestPTYProtocol.CmdResponse command(
          com.google.protobuf.RpcController controller,
          com.lenovo.husky.docker.TestPTYProtocol.CmdRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.lenovo.husky.docker.TestPTYProtocol.CmdResponse command(
          com.google.protobuf.RpcController controller,
          com.lenovo.husky.docker.TestPTYProtocol.CmdRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.lenovo.husky.docker.TestPTYProtocol.CmdResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.lenovo.husky.docker.TestPTYProtocol.CmdResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:PTYService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CmdRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CmdRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CmdResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CmdResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016test_pty.proto\"\032\n\nCmdRequest\022\014\n\004body\030\001" +
      " \001(\014\"\033\n\013CmdResponse\022\014\n\004body\030\001 \001(\01424\n\nPTY" +
      "Service\022&\n\007command\022\013.CmdRequest\032\014.CmdRes" +
      "ponse0\001B0\n\027com.lenovo.husky.dockerB\017Test" +
      "PTYProtocol\210\001\001\240\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CmdRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CmdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CmdRequest_descriptor,
        new java.lang.String[] { "Body", });
    internal_static_CmdResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CmdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CmdResponse_descriptor,
        new java.lang.String[] { "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
